default:
  http_metas:
    content-type: text/html

  metas:
    title:        ForTrend
    robots:       index, follow
    description:  ForTrend
    keywords:     ForTrend
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
